services:
  react-tailwind-ts:
    container_name: react-tailwind-ts
    build:
      context: ./react-tailwind-ts
    ports:
      - 3003:3003
    volumes:
      - ./react-tailwind-ts:/app
      - react-tailwind-ts-node_modules:/app/node_modules
    env_file:
      - ./react-tailwind-ts/.env
  react-mui-js:
    container_name: react-mui-js
    build:
      context: ./react-mui-js
    ports:
      - 3002:3002
    volumes:
      - ./react-mui-js:/app
      - react-mui-js-node_modules:/app/node_modules
    env_file:
      - ./react-mui-js/.env
volumes:
  react-tailwind-ts-node_modules:
  react-mui-js-node_modules:
